<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
        <head>
                <title>Winery Database</title>
                <!--Nathan Dalby s3236863-->
                <link type="text/css" rel="stylesheet" href="style.css" />
                <script type="text/javascript" src="wine.js"></script>
        </head>

        <body>
        <div id="wrapper">


